version: 2
variables:
  prepare_conda: &prepare_conda
    run:
      name: Install from dev-requirements.yml
      command: |
        apt-get update
        apt-get install -y build-essential
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda install cookiecutter -c conda-forge 
        conda install conda-build

  run_tests: &run_tests
    run:
      name: Run tests
      command: |
        cd ..
        cookiecutter repo --overwrite-if-exists --no-input
        cd cpptools
        conda env create -f cpptools-dev-requirements.yml
        source activate cpptools-dev-requirements
        mkdir build
        cd build
        cmake ..
        make -j2
        make python-test
        cd ..

  run_test_script: &run_test_script
    run:
      name: Run tests
      command: |
        ./ci_scripts/citest.sh repo



  run_conda_build: &run_conda_build
    run:
      name: Run conda build
      command: |
        conda build recipe -c conda-forge

jobs:
  test_job:
    docker:
     - image: continuumio/miniconda3:4.5.12
    working_directory: ~/repo
    steps:
      - checkout
      - *prepare_conda
      - *run_tests

  test_job_sh:
    docker:
     - image: continuumio/miniconda3:4.5.12
    working_directory: ~/repo
    steps:
      - checkout
      - *run_test_script

  conda_build_job:
    docker:
     - image: condaforge/linux-anvil:latest
    working_directory: ~/repo
    steps:
      - checkout
      - *prepare_conda
      - *run_conda_build

workflows:
  version: 2

  my_test:
    jobs:
      - test_job_sh
      - test_job
      - conda_build_job

  nightly-test:
    triggers:
       - schedule:
            cron: "0 0 * * *"
            filters:
              branches:
                only:
                  - master
    jobs:
       - test_job_sh
       - test_job
       - conda_build_job
