version: 2
variables:


  install_build_essential: &install_build_essential
    run:
      name: Install Build essential
      command: |
        apt-get update
        apt-get install -y build-essential


  prepare_conda: &prepare_conda
    run:
      name: Install from dev-requirements.yml
      command: |
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda install cookiecutter -c conda-forge 


  run_tests: &run_tests
    run:
      name: Run tests
      command: |
        cd ..
        cookiecutter repo --overwrite-if-exists --no-input
        cd cpptools
        conda env create -f cpptools-dev-requirements.yml
        source activate cpptools-dev-requirements
        mkdir build
        cd build
        cmake ..
        make -j2
        make cpp-test
        make python-test
        cd ..

  run_test_conda_build: &run_test_conda_build
    run:
      name: Run tests
      command: |
        conda install conda-build make
        cd ..
        cookiecutter repo --overwrite-if-exists --no-input
        cd cpptools
        conda build recipe -c conda-forge

  update_conda: &update_conda
    run:
      name: update conda
      command: |
        conda update -q conda 
        conda init bash


  run_test_script: &run_test_script
    run:
      name: Run test scripts
      command: |
        conda init bash
        sh tests/test_project.sh repo


jobs:
  test_job:
    docker:
     - image: continuumio/miniconda3:4.5.12
    working_directory: ~/repo
    steps:
      - checkout
      - *install_build_essential
      - *prepare_conda
      - *run_tests

  test_conda_build_job:
    docker:
     - image: continuumio/miniconda3:4.5.12
    working_directory: ~/repo
    steps:
      - checkout
      - *install_build_essential
      - *prepare_conda
      - *run_test_conda_build


  test_ci_test_script:
    docker:
     - image: continuumio/miniconda3:4.5.12
    working_directory: ~/repo
    steps:
      - checkout
      - *install_build_essential
      - *update_conda
      - *run_test_script

workflows:
  version: 2

  my_test:
    jobs:
      - test_job
      - test_conda_build_job
      - test_ci_test_script

  nightly-test:
    triggers:
       - schedule:
            cron: "0 0 * * *"
            filters:
              branches:
                only:
                  - master
    jobs:
       - test_job
       - test_conda_build_job]
       - test_ci_test_script