{% set name = "{{cookiecutter.conda_package_name}}" %}
{% set version = "0.1.0" %}
#{% set sha256 = "b2ada6f86faf5c9032e8b1a7b8cc0dff68a229e90ad80b366f5564fec03caa17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../
  #fn: ad3-{{ version }}.tar.gz
  #url: https://github.com/DerThorsten/AD3/archive/{{ version }}.tar.gz
  #sha256: {{ sha256 }}


build:
  number: 0

requirements:
  build:
    - toolchain
    - cmake
    - eigen


test:
  commands:
    - test -d ${PREFIX}/include/ad3           # [unix]
    - test -f ${PREFIX}/include/ad3/Factor.h  # [unix]
    - if exist %LIBRARY_PREFIX%\include\ad3\Factor.h (exit 0) else (exit 1)  # [win]

about:
  home:  https://github.com/{{cookiecutter.github_user_name}}/{{cookiecutter.github_project_name}}
  license: GPL3
  license_family: GPL3
  license_file: LICENSE
  summary: '{{cookiecutter.summary}}'
  description: '{{cookiecutter.description}}'
  documentation_url: https://readthedocs.org/projects/{{cookiecutter.readthedocs_package_name}}/
  dev_url: https://github.com/{{cookiecutter.github_user_name}}/{{cookiecutter.github_project_name}}

extra:
  recipe-maintainers:
    - {{cookiecutter.full_name}}

