package:
  name: {{cookiecutter.conda_package_name}}
  version: 0.1.0

source:
  path: ../



build:
  number: 0

requirements:
  build:
    - cmake >=3.1

test:
  commands:
    - test -d ${PREFIX}/include/{{cookiecutter.cpp_root_folder_name}}           # [unix]
    - test -f ${PREFIX}/include/{{cookiecutter.cpp_root_folder_name}}/{{ cookiecutter.package_name}}.hpp # [unix]
    - if exist %LIBRARY_PREFIX%\include\{{cookiecutter.cpp_root_folder_name}}\{{ cookiecutter.package_name}}.hpp (exit 0) else (exit 1)  # [win]



about:
  home:  https://github.com/{{cookiecutter.github_user_name}}/{{cookiecutter.github_project_name}}
  {% if cookiecutter.open_source_license == 'MIT license' -%}
  license: MIT
  license_family: MIT
  {% elif cookiecutter.open_source_license == 'BSD license' %}
  license: BSD 3-Clause
  license_family: BSD
  {% elif cookiecutter.open_source_license == 'ISC license' -%}
  license: ISC
  license_family: ISC
  {% elif cookiecutter.open_source_license == 'Apache Software License 2.0' -%}
  license: Apache
  license_family: Apache
  {% elif cookiecutter.open_source_license == 'GNU General Public License v3' -%}
  license: GPL
  license_family: GPL
  {% endif %}
  summary: '{{cookiecutter.summary}}'
  description: '{{cookiecutter.description}}'
  documentation_url: https://readthedocs.org/projects/{{cookiecutter.readthedocs_package_name}}/
  dev_url: https://github.com/{{cookiecutter.github_user_name}}/{{cookiecutter.github_project_name}}

extra:
  recipe-maintainers:
    - {{cookiecutter.full_name}}

