version: 2
variables:


  install_build_essential: &install_build_essential
    run:
      name: Install from dev-requirements.yml
      command: |
        apt-get update
        apt-get install -y build-essential


  prepare_conda: &prepare_conda
    run:
      name: Install from dev-requirements.yml
      command: |
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda install cookiecutter -c conda-forge 


  run_tests: &run_tests
    run:
      name: Run tests
      command: |
        conda env create -f {{cookiecutter.package_name}}-dev-requirements.yml
        source activate {{cookiecutter.package_name}}-dev-requirements
        mkdir build
        cd build
        cmake ..
        make -j2
        make cpp-test
        {% if cookiecutter.python_bindings == 'yes' -%}
        make python-test
        {% endif %}
        cd ..

  run_test_conda_build: &run_test_conda_build
    run:
      name: Run tests
      command: |
        conda install conda-build make
        conda build recipe -c conda-forge


jobs:
  test_job:
    docker:
     - image: continuumio/miniconda3:4.5.12
    working_directory: ~/repo
    steps:
      - checkout
      - *install_build_essential
      - *prepare_conda
      - *run_tests

  test_conda_build_job:
    docker:
     - image: continuumio/miniconda3:4.5.12
    working_directory: ~/repo
    steps:
      - checkout
      - *install_build_essential
      - *prepare_conda
      - *run_test_conda_build


workflows:
  version: 2

  my_test:
    jobs:
      - test_job
      - test_conda_build_job

  nightly-test:
    triggers:
       - schedule:
            cron: "0 0 * * *"
            filters:
              branches:
                only:
                  - master
    jobs:
       - test_job
       - test_conda_build_job